### ISSUE TITLE
Downloading maps doesn't start

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [andreynovikov/trekarta#63]
I'm using LineageOS 15 (Android 8) and Trekarta 2019.01 (FDroid). If I select some regions to download, they keep marked green in the map manager, but doesn't download. There is no progress bar or something like that - neither in the app nor in a notification.

**Comment by ingmar** [comment]
Same on my phone, also Trekarta 2019.01 from F-Droid. Android 8.1.0. Waited a couple hours and no progress.

**Comment by andreynovikov** [comment]
Do not see any issues. Did it download base map? Did it download map index (the sizes and dates are displayed in map manager)? Can you manually download a by browser (from the phone!)? Here is a link: https://trekarta.info/maps/basemap.mtiles

**Comment by ingmar** [comment]
A few hours later a notification popped up with a percent bar showing downloading of the base map (which, once it started, went pretty quick), and later still I got two of the four areas selected for download. The final two are still missing and no indication of any download activity. It all seems to take extremely long - perhaps connectivity/server issues?

The direct link works, although is quite slow (5 kB/s). Downloads from elsewhere are much faster. I happen to have a VM at Transip myself, and am getting around 150 kB/s from there.

**Comment by andreynovikov** [comment]
This is something with Android Download Manager. Trekarta does not download anything itself. It only issues requests to Download Manager and waits for it to return downloaded data.

**Comment by andreynovikov** [comment]
On my devices downloads are extremely fast.

**Comment by ingmar** [comment]
> This is something with Android Download Manager. Trekarta does not download anything itself. It only issues requests to Download Manager and waits for it to return downloaded data.

Got it. It seems to have been caused by Blokada for some reason (Adblocker, with default blocking list). I had to add Trekarta to the Blokada whitelist and new maptiles downloaded fine from then on.

There was still a problem with maptiles that were already queued for download being stuck with no way to retry them. Tiles that are queued but not yet downloaded (dark green on the tile selector interface) can't be removed by long-pressing, which may be useful to some. I've just reset the app and re-downloaded everything, which worked fine.

Nice app 👍
