### ISSUE TITLE
Add a legend

### ISSUE THREAD

**Issue by 29jm** [andreynovikov/trekarta#70]
First let me say that I love this app, thanks.
Right now there is no way to identify symbols appearing on the map without having to guess.
I suggest adding a legend, perhaps accessible from a new entry in the menu that appears when long pressing the "layers" icon (fourth from the left on the bottom). Something like in https://www.wanderreitkarte.de/index.php?lang=en (here named "Map key").

**Comment by hungerburg** [comment]
The easiest probably was a patch of land, maybe an island in the oceans, at 0/0 perhaps, where all the different ways are drawn and named after their tags

**Comment by andreynovikov** [comment]
Currently working hard on it. Legend can be found in latest beta. It adopts to selected map style and activity.

**Comment by andreynovikov** [comment]
I've used [OpenAndroMaps styling](https://www.openandromaps.org/en/legend/elevate-mountain-hike-theme) as a starting point for coloring as it's standard de facto for such maps. But as I've mentioned in another issue, I can not create non-even stripples. That's why I had to use that sophisticated color codding for T4-T6 trails.

**Comment by andreynovikov** [comment]
Implemented in 2019.09
